#!/usr/bin/env python3
import os
import sys
import time
import random


def Prandom():
  array1 = [
      'a', 'b', 'c', 'd', 'e', 'f', 'g',
      'h', 'i', 'j', 'k', 'l', 'm', 'n',
      'o', 'p', 'q', 'r', 's', 't', 'u',
      'v', 'w', 'x', 'y', 'z',

      'A', 'B', 'C', 'D', 'E', 'F', 'G',
      'H', 'I', 'J', 'K', 'L', 'M', 'N',
      'O', 'P', 'Q', 'R', 'S', 'T', 'U',
      'V', 'W', 'X', 'Y', 'Z',

      '1', '2', '3', '4', '5',
      '6', '7', '8', '9', '0',

      '!', '"', '£', '$', '%', '^',
      '&', '*', '(', ')', '_', '+',
      '[', ']', ';', '\'', '#',
      ',', '.', '/', '\\', '`',
      '{', '}', ':', '@', '~',
      '<', '>', '?', '|', '¬',
    ]

  to_print = random.choice(array1) + random.choice(array1)

  for i in range(26):
    to_print = to_print + random.choice(array1)

  return to_print



def Main():
  while True:
    os.system('clear; clear')

    for i in range(10):
      print(Prandom())

    time.sleep(0.1)



if __name__ == '__main__':
  Main()
